### ISSUE TITLE
Poznámky k dalšímu vývoji aplikace

### ISSUE THREAD

**Issue by mduda100871** [ceskaexpedice/K5Journals#21]
Zdravím,

zprovoznili jsme poslední verzi aplikace v ostrém nasazení. V této chvíli k tomu mám zatím dvě doporučení/požadavky pro další vývoj z pohledu systémového admina.

1) Nasazení Solr 8 - aplikaci se mi na něm nepodařilo rozběhnout. Problém spočívá zřejmě ve verzích jar knihoven distribuovaných v balíčku se schématy a konfigurací jednotlivých jader. Do logu Solru padá tato výjimka:
```
2020-01-27 00:00:48.104 ERROR (coreContainerWorkExecutor-2-thread-1) [   ] o.a.s.c.CoreContainer Error waiting for SolrCore to be loaded on startup => java.lang.NoClassDefFoundError: org/apache/lucene/analysis/util/MultiTermAwareComponen
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
java.lang.NoClassDefFoundError: org/apache/lucene/analysis/util/MultiTermAwareComponent
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:550) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:458) ~[?:?]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:452) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:451) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:899) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.apache.lucene.util.SPIClassIterator.next(SPIClassIterator.java:156) ~[?:?]
        at org.apache.lucene.analysis.util.AnalysisSPILoader.reload(AnalysisSPILoader.java:86) ~[?:?]
        at org.apache.lucene.analysis.util.CharFilterFactory.reloadCharFilters(CharFilterFactory.java:73) ~[?:?]
        at org.apache.solr.core.SolrResourceLoader.reloadLuceneSPI(SolrResourceLoader.java:255) ~[?:?]
        at org.apache.solr.core.SolrResourceLoader.<init>(SolrResourceLoader.java:196) ~[?:?]
        at org.apache.solr.core.ConfigSetService$Default.createCoreResourceLoader(ConfigSetService.java:183) ~[?:?]
        at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:74) ~[?:?]
        at org.apache.solr.core.CoreContainer.getConfigSet(CoreContainer.java:1341) ~[?:?]
        at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:1288) ~[?:?]
        at org.apache.solr.core.CoreContainer.lambda$load$13(CoreContainer.java:788) ~[?:?]
        at com.codahale.metrics.InstrumentedExecutorService$InstrumentedCallable.call(InstrumentedExecutorService.java:202) ~[metrics-core-4.0.5.jar:4.0.5]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:210) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.analysis.util.MultiTermAwareComponent
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:899) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 29 more

```
Skončil jsem tedy prozatím na verzi Solru 6.6.6 => potřeba vyladit pro Solr 8.

2) Je potřeba implementovat nějaký migrační nástroj (klidně i v příkazové řádce), který bude zajišťovat migraci Solr indexu - něco jako migrátor indexu v Krameriovi.  To je důležité pro případ upgradů Solru, případně při změnách schématu. Nyní jsem data přenášel z testovací instance do ostré pomocí snapshotů indexu a není to úplně ono.

3) Jak Solr, tak aplikaci provozuji na OpenJDK - konkrétně Solr na verzi 8 a aplikaci na verzi 11. Tiše jsem předpokládal, že je OpenJDK podporováno, ale bylo by dobré to explicitně uvést i na wiki mezi systémové požadavky.

MD

**Comment by kerschfilip** [comment]
@albertoh vím, že tohle je staré issue, ale můžete prosím v souvislosti s aktuálně připravovanou verzí shrnout na wiki současný stav a popis instalace? - některé komponenty už se upgradovaly (#42) a v souvislosti se #74 bude potřeba instalovat nodejs, tak aby to bylo někde popsané, prosím.

prosím taky komentáře k těm třem bodům, co sem dal @mduda100871
